% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function gui_handle = demo(app)
%% Function to create the main window of the GUI (to select map, bicrystal or meshing interface)
% author: d.mercier@mpie.de

%% Initialization
try
    get_stabix_root; % ensure that environment is set
catch
    [startdir, dummy1, dummy2] = fileparts(mfilename('fullpath'));
    cd(startdir);
    commandwindow;
    path_management;
end

gui.config = get_config;

gui.description = 'Slip transmission analysis in crystal plasticity';
gui.module_name = 'Demo';

%% Main Window Configuration
gui.handles.MainWindow = figure('NumberTitle', 'off',...
    'PaperUnits', get(0,'defaultfigurePaperUnits'),...
    'Color', [0.9 0.9 0.9],...
    'Colormap', get(0,'defaultfigureColormap'),...
    'InvertHardcopy', get(0,'defaultfigureInvertHardcopy'),...
    'PaperPosition', [0 7 50 15],...
    'Position', ...
    figure_position([0.02 0.3 pixelwidth2normalizedwidth(300) 1.6]), ...
    'MenuBar', 'none', ...
    'ToolBar', 'none');

gui.title_str = set_gui_title(gui);

%% Title of the GUI
btm = 0.85;
hu = 0.05;
lft = 0.05;
wid = 0.9;

gui.handles.title_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [lft btm wid 2.7*hu],...
    'String', {[gui.config.toolbox_name, ' ', ...
    gui.config.toolbox_version_str], gui.description},...
    'FontWeight', 'bold',...
    'FontSize', 12,...
    'HorizontalAlignment', 'center');

%% Run grain boundary inclination toolbox
btm = btm - 2.1*hu;
gui.handles.pbgbinc_interface = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [lft btm wid 1.8*hu],...
    'BackgroundColor', [0.9 0.6 0.9],......
    'String', 'Grain Boundary Inclination',...
    'Callback', 'A_gui_gbinc');

%% Run map interface to plot a map of grains with data From TSL
btm = btm - 1.8*hu;
gui.handles.pbinterfaceTSL = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [lft btm wid 1.8*hu],...
    'BackgroundColor', [0.2 0.8 0],......
    'String', 'Analyze an EBSD map',...
    'Callback', 'A_gui_plotmap');

%% Run bicrystal interface
btm = btm - 1.8*hu;
gui.handles.pbBicrystal = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [lft btm wid 1.8*hu],...
    'BackgroundColor', [0.2 0.8 1],...
    'String', 'Analyze a bicrystal',...
    'Callback', 'A_gui_plotGB_Bicrystal');

%% Finite element preprocessing
btm = btm - 1.6*hu;
gui.handles.strinterfaceman = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [lft btm wid 0.05],...
    'String', 'Finite element preprocessing');

top = 0.38;
hu = 0.1;
color_FE = [0.7 0.7 1];

% SX set up
gui.handles.pbBX_meshing = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [lft top wid hu],...
    'BackgroundColor', color_FE,...
    'String', 'Single crystal indentation',...
    'Callback', 'A_preCPFE_windows_indentation_setting_SX');

% BX set up
gui.handles.pbSX_meshing = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [lft top-1*hu wid hu],...
    'BackgroundColor', color_FE,...
    'String', 'Bicrystal indentation',...
    'Callback', 'A_preCPFE_windows_indentation_setting_BX');

%% Properties of buttons
set([gui.handles.pbgbinc_interface,...
    gui.handles.pbinterfaceTSL,...
    gui.handles.pbBicrystal,...
    gui.handles.strinterfaceman, ...
    gui.handles.pbBX_meshing, ...
    gui.handles.pbSX_meshing], ...
    'FontWeight','bold', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 10);

%% Logos of MPIE & MSU
gui.handles.plotlogoMPIE_axes = axes('Parent', gcf,...
    'Position', [0.2 0.03 0.55 0.36],...
    'CameraPositionMode', get(0,'defaultaxesCameraPositionMode'),...
    'Color', get(0,'defaultaxesColor'),...
    'ColorOrder', get(0,'defaultaxesColorOrder'),...
    'LooseInset', [0.13 0.11 0.095 0.075],...
    'XColor', get(0,'defaultaxesXColor'),...
    'YColor', get(0,'defaultaxesYColor'),...
    'ZColor', get(0,'defaultaxesZColor'),...
    'Tag', 'axes1');

[logo]  = imread('logo_MPIE_MSU.bmp');
image(logo); % doesn't need image toolbox
axis off; % Remove axis ticks and numbers
axis image; % Set aspect ratio to obtain square pixels

%% Clear all & Save & Quit & Help
btm = 0.03;
gui.handles.pb_help = uicontrol('Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.05 btm 0.35 hu],...
    'String', 'Documentation',...
    'Callback', ['gui = guidata(gcf); ' ...
    'webbrowser(gui.config.doc_path_root)']);

gui.handles.pb_sourcecode = uicontrol('Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.4 btm 0.3 hu],...
    'String', 'Source code',...
    'Callback', ['gui = guidata(gcf); ' ...
    'webbrowser(gui.config.repository_url)']);

gui.handles.pb_contact = uicontrol('Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.7 btm 0.25 hu],...
    'String', 'Contact',...
    'Callback', ['commandwindow; ' ...
    'fprintf(''### STABiX contact ###\nE-mail '...
    'to c.zambaldi@mpie.de or d.mercier@mpie.de\n'')']);

set([gui.handles.pb_help, ...
    gui.handles.pb_sourcecode, ...
    gui.handles.pb_contact], ...
    'FontWeight','bold', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 8);
    
guidata(gcf, gui);

gui_handle = gcf;

if nargin > 0
    if strcmpi(app, 'map')
        A_gui_plotmap;
    elseif strcmpi(app, 'indsx')
        A_preCPFE_windows_indentation_setting_SX;
    elseif strcmpi(app, 'indbx')
        A_preCPFE_windows_indentation_setting_BX;
    end
end

%% Set logo of the GUI
java_icon_gui;

end