% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function gui_handle = demo
%% Function to create the main window of the GUI (to select map, bicrystal or meshing interface)
% author: d.mercier@mpie.de

%% Initialization
try
    get_stabix_root; % ensure that environment is set
catch
    [startdir, dummy1, dummy2] = fileparts(mfilename('fullpath'));
    cd(startdir);
    commandwindow
    path_management
end


%% Set Matlab
gui.config = load_YAML_config_file;
gui.config.username = get_username;
gui.description = 'Slip transmission analysis in crystal plasticity';
gui.version_str = num2str(gui.config.version_toolbox);
gui.module_name = 'Demo';

%% Main Window Configuration
gui.handles.MainWindow = figure('NumberTitle', 'off',...
    'PaperUnits', get(0,'defaultfigurePaperUnits'),...
    'Color', [0.9 0.9 0.9],...
    'Colormap', get(0,'defaultfigureColormap'),...
    'InvertHardcopy', get(0,'defaultfigureInvertHardcopy'),...
    'PaperPosition', [0 7 50 15],...
    'Position', figure_position([0.02 0.3 0.28 1.6]), ...
    'MenuBar', 'none', ...
    'ToolBar', 'none');

gui.title_str = set_gui_title(gui);

%% Title of the GUI
btm = 0.85;
hu = 0.05;
gui.handles.title_GUI = uicontrol('Parent', gui.handles.MainWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.05 btm 0.9 2.7*hu],...
    'String', {[gui.config.toolbox_name, ' ', gui.version_str], gui.description},...%get(gcf, 'name'), ...
    'FontWeight', 'bold',...
    'FontSize', 12,...
    'HorizontalAlignment', 'center');

%% Run map interface to plot a map of grains with data From TSL
% gui.handles.strinterfaceTSL = uicontrol('Parent', gui.handles.MainWindow,...
%     'Units', 'normalized',...
%     'Style', 'text',...
%     'Position', [0.05 0.85 0.9 0.05],...
%     'String', 'Import Data from TSL',...
%     'FontWeight', 'bold',...
%     'FontSize', 12,...
%     'HorizontalAlignment', 'center');

btm = btm - hu;
gui.handles.pbinterfaceTSL = uicontrol('Parent', gui.handles.MainWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.05 0.73 0.9 0.1],...
    'BackgroundColor', [0.2 0.8 0],......
    'String', 'Analyze an EBSD map',...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'HorizontalAlignment', 'center',...
    'Callback', 'A_gui_plotmap');

%% Run bicrystal interface
% gui.handles.strinterfaceman = uicontrol('Parent', gui.handles.MainWindow,...
%     'Units', 'normalized',...
%     'Style', 'text',...
%     'Position', [0.05 0.65 0.9 0.05],...
%     'String', 'Bicrystal interface',...
%     'FontWeight', 'bold',...
%     'FontSize', 12,...
%     'HorizontalAlignment', 'center');

gui.handles.pbGBManualInput_UCPlot = uicontrol('Parent', gui.handles.MainWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.05 0.62 0.9 0.1],...
    'BackgroundColor', [0.2 0.8 1],...
    'String', 'Analyze a bicrystal',...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'HorizontalAlignment', 'center',...
    'Callback', 'A_gui_plotGB_Bicrystal');

%% FEM
gui.handles.strinterfaceman = uicontrol('Parent', gui.handles.MainWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.05 0.52 0.9 0.05],...
    'String', 'Finite element preprocessing',...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'HorizontalAlignment', 'center');

lft = 0.05;
top = 0.4;
hu = 0.1;
color_FE = [0.7 0.7 1];
% SX set up
gui.handles.pbBX_meshing = uicontrol('Parent', gui.handles.MainWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [lft top 0.9 hu],...
    'BackgroundColor', color_FE,...
    'String', 'Single crystal indentation',...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'Callback', 'A_preCPFE_windows_indentation_setting_SX');

% BX set up
gui.handles.pbSX_meshing = uicontrol('Parent', gui.handles.MainWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [lft top-1.1*hu 0.9 hu],...
    'BackgroundColor', color_FE,...
    'String', 'Bicrystal indentation',...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'Callback', 'A_preCPFE_windows_indentation_setting_BX');

%% Logos of MPIE & MSU
gui.handles.plotlogoMPIE_axes = axes('Parent', gui.handles.MainWindow,...
    'Position', [0.2 0.03 0.55 0.36],...
    'CameraPositionMode', get(0,'defaultaxesCameraPositionMode'),...
    'Color', get(0,'defaultaxesColor'),...
    'ColorOrder', get(0,'defaultaxesColorOrder'),...
    'LooseInset', [0.13 0.11 0.095 0.075],...
    'XColor', get(0,'defaultaxesXColor'),...
    'YColor', get(0,'defaultaxesYColor'),...
    'ZColor', get(0,'defaultaxesZColor'),...
    'Tag', 'axes1');

[logo, map]  = imread('logo_MPIE_MSU.bmp');
%plotlogoMPIE = imshow(logo, map); % needs image toolbox
plotlogoMPIE = image(logo); % doesn't need image toolbox
axis off; % Remove axis ticks and numbers
axis image; % Set aspect ratio to obtain square pixels


%% Clear all & Save & Quit & Help
btm = 0.03;
gui.handles.pbhelp = uicontrol('Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.05 btm 0.35 hu],...
    'String', 'Documentation',...
    'Callback', 'gui = guidata(gcf); webbrowser(gui.config.doc_path_root)');

gui.handles.pbfinishsav = uicontrol('Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.4 btm 0.3 hu],...
    'String', 'Source code',...
    'Callback', 'gui = guidata(gcf); webbrowser(gui.config.repository_url)');

gui.handles.pb_contact = uicontrol('Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.7 btm 0.25 hu],...
    'String', 'Contact',...
    'HorizontalAlignment', 'center',...
    'Callback', 'commandwindow; fprintf(''### STABiX contact ###\nE-mail to c.zambaldi@mpie.de or d.mercier@mpie.de\n'')');

set([gui.handles.pbhelp, gui.handles.pbfinishsav, gui.handles.pb_contact], ...
    'FontWeight','bold');
    

guidata(gcf, gui);

gui_handle = gui.handles.MainWindow;

end
