% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function list_coordsys = listCoordSys

list_coordsys = {...
    'X right, Y up'; ...
    'X up, Y left'; ...
    'X left, Y down'; ...
    'X down, Y right (TSL default)'; ...
    'X right, Y down'; ...
    'X up, Y right'; ...
    'X left, Y up'; ...
    'X down, Y left'};

end