% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function handles = gui_gbinc_buttons_vickers_indents(x0, hu, wu)
%% Function to create buttons/boxes for the loading/setting of images
% x0: origin of x coordinate
% hu: heigth unit
% wu: width unit

% authors: d.mercier@mpie.de / c.zambaldi@mpie.de

h = uibuttongroup('visible','on','Position',[x0 hu*3.2 wu*3 x0*8]);

x0 = 0.01;
hu = 0.1; % height unit
wu = 0.1; % width unit

%% Get Vickers distance
handles.distance_calculation = set_pushbutton('VICKERS DISTANCE', ...
    [x0 hu wu*3 x0*80], 'gui_gbinc_vickers_distance', h);

handles.indent_str = uicontrol('Parent', h,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [x0*32 hu*5 wu*2 x0*40],...
    'String', 'Vickers indent',...
    'HorizontalAlignment', 'left');

handles.indent_selection = uicontrol('Parent', h,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [x0*32 hu*2 wu*2 x0*40],...
    'String', 'edge|ridge',...
    'BackgroundColor', [1 1 1],...
    'Value', 1);

%% Get thickness of material removed
handles.height_calculation = set_pushbutton('CALCULATION', ...
    [x0*55 hu wu*2 x0*80], 'gui_gbinc_thickness_removed_calculation', h);

handles.height_str = uicontrol('Parent', h,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [x0*77 hu*5 wu*1.5 x0*40],...
    'String', 'Thickness',...
    'HorizontalAlignment', 'left');

handles.height = uicontrol('Parent', h,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [x0*77 hu*2 wu*1.5 x0*40],...
    'BackgroundColor', [1 1 1]);

handles.height_unit = uicontrol('Parent', h,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [x0*92 hu*2 wu x0*40],...
    'String', 'µm',...
    'HorizontalAlignment', 'left');

end