% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function listEdgeDetec = listEdgeDetection
% See http://fr.mathworks.com/help/images/ref/edge.html

listEdgeDetec = {...
    'sobel'; ...
    'prewitt'; ...
    'roberts'; ...
    'canny'; ...
    'log'; ...
    'zerocross'};

end