% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function listColor = listColormap

listColor = {'default'; ... % 'parula'; ... % default from Matlab2014b
    'jet'; ...
    'autumn'; ...
    'bone'; ...
    'colorcube'; ...
	'cool'; ...
	'copper'; ...
	'flag'; ...
	'gray'; ...
	'hot'; ...
	'hsv'; ...
	'lines'; ...
	'pink'; ...
	'prism'; ...
	'spring'; ...
	'summer'; ...
	'white'; ...
	'winter'};



end