% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function listCIF = listCIFFile
% See https://mtex-toolbox.github.io/files/doc/ImportEBSDData.html

listCIF = {...
    'Ag-Silver'; ...
    'Al2O3-Corundum'; ...
    'Al-Aluminum'; ...
    'C-Diamond'; ...
    'Cr-Chromium'; ...
    'Cu-Copper'; ...
    'Fe-Iron-alpha'; ...
    'Fe-Iron-Austenite'; ...
    'Fe-Iron-beta'; ...
    'Fe-Iron-delta'; ...
    'Fe-Iron-gamma'; ...
    'GaAs'; ...
    'Hematite'; ...
    'LaB6'; ...
    'Magnetite'; ...
    'Mg-Magnesium'; ...
    'Mn-Manganese-gamma'; ...
    'Mo-Molybdenum-bcc'; ...
    'Mo-Molybdenum-fcc'; ...
    'NaCl-Halite'; ...
    'Ni-Nickel-cubic'; ...
    'Ni-Nickel-hexagonal'; ...
    'olivin'; ...
    'quartz'; ...
    'Rhabdite'; ...
    'Si-Silicon'; ...
    'Ti-Titanium-alpha'; ...
    'Ti-Titanium-beta'; ...
    'ZrO2-Baddeleyite'};

end