% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function listColor = listColormap
% See http://fr.mathworks.com/help/matlab/ref/colormap.html

listColor = {...
    'default'; ... % 'parula'; ... % default from Matlab2014b
    'jet'; ...
    'autumn'; ...
    'bone'; ...
    'colorcube'; ...
    'cool'; ...
    'copper'; ...
    'flag'; ...
    'gray'; ...
    'hot'; ...
    'hsv'; ...
    'lines'; ...
    'pink'; ...
    'prism'; ...
    'spring'; ...
    'summer'; ...
    'white'; ...
    'winter';...
    'parula';...
    'cold';...
    'DivergingMap 1';...
    'DivergingMap 2';...
    'DivergingMap 3';...
    'DivergingMap 4';...
    'DivergingMap 5'};

end