% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function listImageCorr = listImageCorrection
% See http://fr.mathworks.com/help/images/linear-filtering.html

listImageCorr = {...
    'im2uint16'; ...
    'imfilter'; ...
    'adapthisteq'; ...
    'histeq'; ...
    'decorrstretch'; ...
    'stretchlim'};

end