% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function listEBSD = listEBSDFile
% See https://mtex-toolbox.github.io/files/doc/ImportEBSDData.html

listEBSD = {...
    '*.ang', 'TSL single orientation files (*.ang)'; ...
    '*.txt', 'Bruker single orientation files (*.txt)'; ...
    '*.crc', 'single orientation files (*.crc)'; ...
    '*.csv', 'Oxford single orientation files (*.csv)'; ...
    '*.ctf', 'HKL single orientation files (*.ctf)'; ...
    '*.txt', 'Dram 3d single orientation files (*.txt)'; ...
    '*.DRex', 'single orientation files (*.DRex)'; ...
    '*.h5', 'single orientation files (*.h5)'; ...
    '*.osc', 'single orientation files (*.osc)';...
    '*.csv', 'single orientation files (*.csv)'; ...
    '*.txt', 'ASCII files with Euler angles as columns (*.txt)'};
end