% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function listLocation = listLocation

listLocation = {'North'; ...
    'South'; ...
    'East'; ...
    'West'; ...
    'NorthEast'; ...
    'SouthEast'; ...
    'NorthWest'; ...
    'SouthWest'; ...
	'NorthOutside'; ...
	'SouthOutside'; ...
	'EastOutside'; ...
	'WestOutside'; ...
	'Best'};

end