% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function list_material = listMaterial

list_material = {'Al';...
    'Au';...
    'Be';...
    'Cd';...
    'Co';...
    'Cu';...
    'Fe';...
    'Mg';...
    'Mo';...
    'Nb';...
    'Ni';...
    'Ta';...
    'Ti';...
    'Sn';...
    'Zn';...
    'Zr'};
end