function h_popup = femproc_solver_popup(pos)
gui = guidata(gcf);
h_popup = uicontrol('Units', 'normalized',...
    'Position', pos,...
    'Style', 'popup',...
    'String', gui.config.CPFEM.fem_solvers,...
    'BackgroundColor', [0.9 0.9 0.9],...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'HorizontalAlignment', 'center');
