function femproc_custom_menu_edit_gui(parent, file_loc)
cb_string = sprintf('edit(''%s'')', file_loc);
uimenu(parent, 'Label', 'Edit this GUI', ...
    'Callback', cb_string, ...
    'Separator','on');