% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function [Titlegbdata, Titlegbdatacompl] = femproc_set_title_data(config_map, GB)
%% Script to set the title of data and files produced for CPFEM
% config_map :Configuration from the EBSD map GUI (sample, etc...)
% GB: Grain boundary number

% authors: d.mercier@mpie.de / c.zambaldi@mpie.de

timestamp = date_time_string(1, 1);

if ~isempty(config_map.Material_ID) && ~isempty(config_map.Sample_ID)
    if strcmp(GB.active_data, 'BX') == 1
        Titlegbdata = strcat(...
            config_map.Material_ID,...
            '_', config_map.Sample_ID,...
            '_BX', num2str(GB.GB_Number),...
            '_grain', num2str(GB.activeGrain),...
            '_', timestamp,...
            '_Incli', num2str(round(GB.GB_Inclination)));
        %'GrA',num2str(GB.GrainA),...
        %'GrB',num2str(GB.GrainB),...
        %'GB_Tra',num2str(round(GB.GB_Trace_Angle)),...
        %strdate,'_',...
        %'_',config_map.simulation_code
        
    elseif strcmp(GB.active_data, 'SX') == 1
        Titlegbdata = strcat(...
            config_map.Material_ID,...
            '_', config_map.Sample_ID,...
            '_SX', num2str(GB.activeGrain),...
            '_', timestamp);
        %'GrA',num2str(GB.GrainA),...
        %'GrB',num2str(GB.GrainB),...
        %'GB_Tra',num2str(round(GB.GB_Trace_Angle)),...
        %strdate,'_',...
        %'_',config_map.simulation_code
        
    end
else
    
    if strcmp(GB.active_data, 'BX') == 1
        Titlegbdata = strcat(...
            'BX', num2str(GB.GB_Number),...
            '_grain', num2str(GB.activeGrain),...
            '_', timestamp,...
            '_Incli', num2str(round(GB.GB_Inclination)));
        %'GrA',num2str(GB.GrainA),...
        %'GrB',num2str(GB.GrainB),...
        %'GB_Tra',num2str(round(GB.GB_Trace_Angle)),...
        %strdate,'_',...
        %'_',config_map.simulation_code
        
    elseif strcmp(GB.active_data, 'SX') == 1
        Titlegbdata = strcat(...
            'SX', num2str(GB.activeGrain),...
            '_', timestamp);
        %'GrA',num2str(GB.GrainA),...
        %'GrB',num2str(GB.GrainB),...
        %'GB_Tra',num2str(round(GB.GB_Trace_Angle)),...
        %strdate,'_',...
        %'_',config_map.simulation_code
    end
end

Titlegbdatacompl = strcat(Titlegbdata,'.mat');

Titlegbdata = char(Titlegbdata);
Titlegbdatacompl = char(Titlegbdatacompl);

end
