% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function femproc_generate_indentation_model_BX
%% Generation of procedure file and material file for CPFE modelling of BX indentation (with GENMAT or DAMASK)
% authors: d.mercier@mpie.de / c.zambaldi@mpie.de

gui_BX = guidata(gcf);

%% Initialization = Set bicrystal and get active GB
if str2num(get(gui_BX.handles.ind_dist_val, 'String')) >= 0
    gui_BX.GB.activeGrain = gui_BX.GB.GrainA;
else
    gui_BX.GB.activeGrain = gui_BX.GB.GrainB;
end
[gui_BX.GB.Titlegbdata, gui_BX.GB.Titlegbdatacompl] = femproc_set_title_data(gui_BX.config_map, gui_BX.GB);

guidata(gcf, gui_BX);
femproc_indentation_setting_BX;
gui_BX = guidata(gcf); guidata(gcf, gui_BX);

femproc_save_data(2);
gui_BX = guidata(gcf); guidata(gcf, gui_BX);
%gui_BX.variables
%gui_BX.GB

%% Creation of the python file run in the command line window to generate procedure file for the bicrystal
scriptname_bicrystal = sprintf('%s_FEM_model_parameters.py', gui_BX.GB.Titlegbdatacompl);

fid = fopen([scriptname_bicrystal,'_old.py'], 'w+');
fprintf(fid, '# Generated by matlab/gui/femproc_generate_model.m --- DO NOT EDIT\n');
fprintf(fid, 'import sys\n');
fprintf(fid, 'p=''%s'' \n', gui_BX.config_CPFEM.msc_module_path);
fprintf(fid, 'if p not in sys.path: sys.path.insert(0,p) \n');
fprintf(fid, 'import scipy.io\n');
fprintf(fid, 'gb_data = scipy.io.loadmat(''%s'')\n', gui_BX.GB.Titlegbdata);
fprintf(fid, 'import msc\n');
fprintf(fid, 'import msc.bicrystal_indentation_model_from_MatlabGUI as gb_ind\n');
fprintf(fid, 'gb_ind.doit(gb_data, proc_path=r''%s'')\n', fullfile(gui_BX.config_CPFEM.proc_file_path, gui_BX.GB.Titlegbdata, ''));
fclose(fid);

py = {''};
py{1} = sprintf('# Generated by %s (%s) %s, %s.m', ...
    gui_BX.toolbox_name, gui_BX.version_str, gui_BX.module_name, mfilename);
py{end+1} = 'import sys';
py{end+1} = sprintf('p=''%s'' ', gui_BX.config_CPFEM.msc_module_path);
py{end+1} = sprintf('if p not in sys.path: sys.path.insert(0,p) \n');
py{end+1} = sprintf('from msc.proc.bicrystal import BicrystalIndent');
py{end+1} = sprintf('BicrystalIndent.__module__');
py{end+1} = sprintf('import msc.tools');
py{end+1} = sprintf('Titlegbdata = ''%s'' ', gui_BX.GB.Titlegbdata);
py{end+1} = sprintf('BicrystalIndent.CODE = ''%s''', gui_BX.config_CPFEM.simulation_code);
py{end+1} = sprintf('BicrystalIndent.MENTATVERSION = %.1f', gui_BX.config_CPFEM.fem_interface); 
py{end+1} = 'indent = BicrystalIndent(';
py{end+1} = sprintf('modelname = Titlegbdata,');
py{end+1} = sprintf('trace_ang =  %.3f,', gui_BX.GB.GB_Trace_Angle);
py{end+1} = sprintf('inclination = %.2f,', gui_BX.GB.GB_Inclination);
py{end+1} = sprintf('d = %e,', gui_BX.variables.ind_dist);
py{end+1} = sprintf('ind_size = 1.,');
py{end+1} = sprintf('h_indent = %.5f,', gui_BX.variables.h_indent);
py{end+1} = sprintf('tipRadius = %.5f,', gui_BX.variables.tipRadius);
py{end+1} = sprintf('coneAngle = %.5f,', gui_BX.variables.coneAngle);
py{end+1} = sprintf('wid = %.5f,', gui_BX.variables.w_sample);
py{end+1} = sprintf('hei = %.5f,', gui_BX.variables.h_sample);
py{end+1} = sprintf('len = %.5f,', gui_BX.variables.len_sample);
py{end+1} = sprintf('box_elm_nx = %i,', gui_BX.variables.box_elm_nx);
py{end+1} = sprintf('box_elm_nz = %i,', gui_BX.variables.box_elm_nz);
py{end+1} = sprintf('box_elm_ny1 = %i,', gui_BX.variables.box_elm_ny1);
py{end+1} = sprintf('box_elm_ny2_fac = %.2f,', gui_BX.variables.box_elm_ny2_fac);
py{end+1} = sprintf('box_elm_ny3 = %i,', gui_BX.variables.box_elm_ny3);
py{end+1} = sprintf('box_bias_x = %.3f,', gui_BX.variables.box_bias_x);
py{end+1} = sprintf('box_bias_z = %.3f,', gui_BX.variables.box_bias_z);
py{end+1} = sprintf('box_bias_y1 = %.3f,', gui_BX.variables.box_bias_y1);
py{end+1} = sprintf('box_bias_y2 = %.3f,', gui_BX.variables.box_bias_y2);
py{end+1} = sprintf('box_bias_y3 = %.3f,', gui_BX.variables.box_bias_y3);
py{end+1} = sprintf('smv = %e,', gui_BX.variables.smv);
py{end+1} = sprintf('lvl = %i,', gui_BX.variables.meshquality);
py{end+1} = sprintf('len_trace = 1.');
py{end+1} = sprintf(')');
proc_path = fullfile(gui_BX.config_CPFEM.proc_file_path, gui_BX.GB.Titlegbdata, '')
proc_path = strrep(proc_path,'\\', '\\\\');
py{end+1} = sprintf('proc_path = ''%s'' ', proc_path);
py{end+1} = sprintf('msc.tools.mkdir_p(proc_path)');
py{end+1} = sprintf('indent.to_file(dst_path=proc_path, dst_name=Titlegbdata + ''.proc'')');
%cellfun(@display, py)

fid = fopen([scriptname_bicrystal], 'w+');
for iln = 1:numel(py)
    fprintf(fid, '%s\n', py{iln});
end
fclose(fid);
%edit(scriptname_bicrystal)

%% Execute the python code that we just generated
cmd = sprintf('%s %s', gui_BX.config_CPFEM.python_executable, ...
    fullfile(pwd, scriptname_bicrystal));
commandwindow;
if ~ isempty(gui_BX.config_CPFEM.pythonpath)
    setenv('PYTHONPATH', gui_BX.config_CPFEM.pythonpath);
end
system(cmd);

%% Definition of path config file
gui_BX.path_config_file = fullfile(gui_BX.config_CPFEM.proc_file_path, gui_BX.GB.Titlegbdata, '');
guidata(gcf, gui_BX);
mkdir(gui_BX.path_config_file);

%% Move files to keep the directory cleaned and organized
% Move YAML file
gui_BX.GB.Titlegbdatacompl_YAML = strcat(gui_BX.GB.Titlegbdatacompl, '.yaml');
%try
%movefile(Titlegbdatacompl_YAML, activeBX.pathnameGF2_BC);
%catch err
%errordlg(err.message);
%end
%delete('random_inputs'); delete('manual_inputs');

% Move Python file
python_procedure_generation_file = strcat(gui_BX.GB.Titlegbdatacompl, '_FEM_model_parameters.py');

try
    movefile(python_procedure_generation_file, gui_BX.path_config_file);
catch err
    errordlg(err.message);
end

femproc_generate_material_files_BX;

% Move .mat file
try
    movefile(gui_BX.GB.Titlegbdatacompl, gui_BX.path_config_file);
catch err
    errordlg(err.message);
end

guidata(gcf, gui_BX);

end
