% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
% $Id: femproc_generate_indentation_model_SX.m 1202 2014-08-05 12:58:13Z d.mercier $
function femproc_generate_indentation_model_SX
%% Generation of procedure file and material file for CPFE modelling of SX indentation (with GENMAT or DAMASK)
% authors: d.mercier@mpie.de / c.zambaldi@mpie.de

gui_SX = guidata(gcf);

%% Initialization = Set single crystal and get active Grain
[gui_SX.GB.Titlegbdata, gui_SX.GB.Titlegbdatacompl] = femproc_set_title_data(gui_SX.config_map, gui_SX.GB);

guidata(gcf, gui_SX);
femproc_indentation_setting_SX;
gui_SX = guidata(gcf); guidata(gcf, gui_SX);

femproc_save_data(1);
gui_SX = guidata(gcf); guidata(gcf, gui_SX);

%% Creation of the python file run in the command line window to generate procedure file for the bicrystal
scriptname_bicrystal = sprintf('%s_FEM_model_parameters.py', gui_SX.GB.Titlegbdatacompl);

fid = fopen(scriptname_bicrystal, 'w+');
fprintf(fid, '# Generated by matlab/gui/femproc_generate_model.m --- DO NOT EDIT\n');
fprintf(fid, 'import os,sys\n');
fprintf(fid, 'p = ''%s'' \n', gui_SX.config_CPFEM.msc_module_path);
fprintf(fid, 'if p not in sys.path: sys.path.insert(0,p) \n');
fprintf(fid, 'import scipy.io\n');
fprintf(fid, 'gb_data = scipy.io.loadmat(''%s'')\n', gui_SX.GB.Titlegbdata);
fprintf(fid, 'print(sys.path)\n');
fprintf(fid, 'print(os.getcwd())\n');
fprintf(fid, 'import msc\n');
fprintf(fid, 'print(msc.__file__)\n');
fprintf(fid, 'import msc.single_crystal_indentation_model_from_MatlabGUI as gb_ind\n');
if ismac || isunix
    fprintf(fid, 'gb_ind.doit(gb_data, proc_path=r''%s/%s'')\n', gui_SX.config_CPFEM.proc_file_path, gui_SX.GB.Titlegbdata);
else
    fprintf(fid, 'gb_ind.doit(gb_data, proc_path=r''%s\\%s'')\n', gui_SX.config_CPFEM.proc_file_path, gui_SX.GB.Titlegbdata);
end
fclose(fid);

%% Execute the Python code that we just generated
cmd = sprintf('%s %s', gui_SX.config_CPFEM.python_executable, fullfile(pwd, scriptname_bicrystal));
commandwindow;
if ~ isempty(gui_SX.config_CPFEM.pythonpath)
    setenv('PYTHONPATH', gui_SX.config_CPFEM.pythonpath);
end
system(cmd);

%% Definition of path config file
if ismac || isunix
    gui_SX.path_config_file = strcat(gui_SX.config_CPFEM.proc_file_path, '/', gui_SX.GB.Titlegbdata, '/');
else
    gui_SX.path_config_file = strcat(gui_SX.config_CPFEM.proc_file_path, '\', gui_SX.GB.Titlegbdata);
end
guidata(gcf, gui_SX);
mkdir(gui_SX.path_config_file);

%% Move files to keep the directory cleaned and organized
% Move YAML file
gui_SX.GB.Titlegbdatacompl_YAML = strcat(gui_SX.GB.Titlegbdatacompl, '.yaml');
%try
%movefile(Titlegbdatacompl_YAML, activeSX.pathnameGF2_BC);
%catch err
%errordlg(err.message);
%end
%delete('random_inputs'); delete('manual_inputs');

% Move Python file
python_procedure_generation_file = strcat(gui_SX.GB.Titlegbdatacompl, '_FEM_model_parameters.py');

try
    movefile(python_procedure_generation_file, gui_SX.path_config_file);
catch err
    errordlg(err.message);
end

if gui_SX.GB.activeGrain == gui_SX.GB.GrainA
    gui_SX.GB.activeGrain_eul = gui_SX.GB.eulerA;
elseif gui_SX.GB.activeGrain == gui_SX.GB.GrainB
    gui_SX.GB.activeGrain_eul = gui_SX.GB.eulerB;
end
guidata(gcf, gui_SX);

femproc_generate_material_files_SX;

% Move .mat file
try
    movefile(gui_SX.GB.Titlegbdatacompl, gui_SX.path_config_file);
catch err
    errordlg(err.message);
end

guidata(gcf, gui_SX);

end