% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function h_popup = preCPFE_solver_popup(pos)
%% Function used to create popup menu for CPFE solver
% pos: Position of the popup menu

gui = guidata(gcf);
h_popup = uicontrol('Units', 'normalized',...
    'Position', pos,...
    'Style', 'popup',...
    'String', gui.config.CPFEM.fem_solvers,...
    'BackgroundColor', [0.9 0.9 0.9],...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'HorizontalAlignment', 'center');

end