% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function preCPFE_mesh_level(ratio)
%% Function to set the mesh level

gui = guidata(gcf);

lvl = ...
    str2num(get(gui.handles.other_setting.mesh_quality_lvl_val, 'String'));

lvl = lvl + ...
    lvl * ratio;

set(gui.handles.other_setting.mesh_quality_lvl_val, ...
    'String', num2str(round(10*lvl)/10));

if strfind(gui.description, 'bicrystal')
    gui.variables.box_elm_nx  = ...
        round(str2num(get(gui.handles.mesh.box_elm_nx_val, 'String'))*lvl);
    gui.variables.box_elm_nz  = ...
        round(str2num(get(gui.handles.mesh.box_elm_nz_val, 'String'))*lvl);
    gui.variables.box_elm_ny1 = ...
        round(str2num(get(gui.handles.mesh.box_elm_ny1_val, 'String'))*lvl);
    gui.variables.box_elm_ny2 = ...
        round(str2num(get(gui.handles.mesh.box_elm_ny2_val, 'String'))*lvl);
    gui.variables.box_elm_ny3 = ...
        round(str2num(get(gui.handles.mesh.box_elm_ny3_val, 'String'))*lvl);
    
    set(gui.handles.mesh.box_elm_nx_val, ...
        'String', num2str(gui.variables.box_elm_nx));
    set(gui.handles.mesh.box_elm_nz_val, ...
        'String', num2str(gui.variables.box_elm_nz));
    set(gui.handles.mesh.box_elm_ny1_val, ...
        'String', num2str(gui.variables.box_elm_ny1));
    set(gui.handles.mesh.box_elm_ny2_val, ...
        'String', num2str(gui.variables.box_elm_ny2));
    set(gui.handles.mesh.box_elm_ny3_val, ...
        'String', num2str(gui.variables.box_elm_ny3));
    
elseif strfind(gui.description, 'single')
    gui.variables.box_elm_nx = ...
        round(str2num(get(gui.handles.mesh.box_elm_nx_val, 'String'))*lvl);
    gui.variables.box_elm_nz = ...
        round(str2num(get(gui.handles.mesh.box_elm_nz_val, 'String'))*lvl);
    gui.variables.radial_divi = ...
        round(str2num(get(gui.handles.mesh.radial_divi_val, 'String'))*lvl);
    
    set(gui.handles.mesh.box_elm_nx_val, ...
        'String', num2str(gui.variables.box_elm_nx));
    set(gui.handles.mesh.box_elm_nz_val, ...
        'String', num2str(gui.variables.box_elm_nz));
    set(gui.handles.mesh.radial_divi_val, ...
        'String', num2str(gui.variables.radial_divi));
    
end

gui.variables.mesh_quality_lvl = lvl;

guidata(gcf, gui);

end