% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function BX_num_elements = ...
    preCPFE_indentation_number_elements_BX
%% Calculation of the number of elements in the modelling of bicrystal indentation
% authors: d.mercier@mpie.de / c.zambaldi@mpie.de

gui_BX = guidata(gcf);

if gui_BX.variables.ind_dist ~= 0
    BX_num_elements = ...
        2 * gui_BX.variables.box_elm_nx * gui_BX.variables.box_elm_nz *...
        (gui_BX.variables.box_elm_ny1 ...
        + (abs(gui_BX.variables.ind_dist) * gui_BX.variables.box_elm_ny2_fac) ...
        + gui_BX.variables.box_elm_ny3);
else
    BX_num_elements = ...
        2 * gui_BX.variables.box_elm_nx * gui_BX.variables.box_elm_nz *...
        (gui_BX.variables.box_elm_ny1 + gui_BX.variables.box_elm_ny3);
end


set(gui_BX.handles.other_setting.num_elem ,'String', ...
    strcat(num2str(BX_num_elements),' elements'));

end