% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function menuBX = plotGB_Bicrystal_custom_menu
%% Add a custom menu item in the GUI menubar
% authors: d.mercier@mpie.de / c.zambaldi@mpie.de

menuBX = uimenu('Label', 'Bicrystal');

custom_menu_help(menuBX);

uimenu(menuBX, 'Label', 'Load a new random bicrystal', ...
    'Callback', 'plotGB_Bicrystal_random_bicrystal', 'Separator','on');
uimenu(menuBX, 'Label', 'Load bicrystal config. file', ...
    'Callback', 'plotGB_Bicrystal_load_YAML_config_file');

uimenu(menuBX, 'Label', 'Save bicrystal pictures', ...
    'Callback', ['gui = guidata(gcf);', ...
    'save_figure(gui.GB.pathnameRB_BC, gcf);', ...
    'set(gcf, ''Color'', [0.9 0.9 0.9]);'], 'Separator','on');
uimenu(menuBX, 'Label', 'Save bicrystal data', ...
    'Callback', ['gui = guidata(gcf);' ...
    'save_data(gui.GB.pathnameRB_BC, gui.GB)']);

uimenu(menuBX, 'Label', 'Show bicrystal conventions', ...
    'Callback', ['gui = guidata(gcf);' ...
    'webbrowser(fullfile(gui.config.doc_path_root,' ...
    'gui.config.doc_path_BXconv_png))'], ...
    'Separator','on');

uimenu(menuBX, 'Label', 'Edit YAML bicrystal config. file', ...
    'Callback', ['gui = guidata(gcf);' ...
    'if isfield(gui, ''GB_YAML'') edit(gui.GB_YAML.filename);', ...
    'else warning_commwin(''No YAML file loaded...'');', ...
    'end'], ...
    'Separator','on');

uimenu(menuBX, 'Label', 'Edit this GUI', ....
    'Callback', 'edit(''A_gui_plotGB_Bicrystal'')');

menuBX_CPFEM = uimenu('Label', 'CPFEM');

uimenu(menuBX_CPFEM, 'Label', 'Indentation test in a bicrystal', ...
    'Callback', 'A_preCPFE_windows_indentation_setting_BX(guidata(gcf))');
uimenu(menuBX_CPFEM, 'Label', 'Indentation test in a Grain A', ...
    'Callback', 'A_preCPFE_windows_indentation_setting_SX(guidata(gcf),1)');
uimenu(menuBX_CPFEM, 'Label', 'Indentation test in a Grain B', ...
    'Callback', 'A_preCPFE_windows_indentation_setting_SX(guidata(gcf),2)');
uimenu(menuBX_CPFEM, 'Label', 'Bending test of a cantilever', ...
    'Callback', ['warning_commwin' ...
    '(''Bending test model not yet implemented...!'', 1)']);
uimenu(menuBX_CPFEM, 'Label', 'Compression test of µ-pillar', ...
    'Callback', ['warning_commwin' ...
    '(''Compression of µ-pillar model not yet implemented...!'', 1)']);

end