% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function plotGB_Bicrystal_set_slips_indices(handle_slip, normal_vector, ...
    direction_vector)
%% Function used to set slip indices (normal and direction vectors)

set(handle_slip, ...
    'String', [ ...
    '(', ...
    num2str(normal_vector), ...
    ') / [', ...
    num2str(direction_vector), ...
    ']']);

end