% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function plotGB_Bicrystal_set_slips_indices(h_slip, n_vector, d_vector)
%% Function used to set slip indices (normal and direction vectors)
% h_slip: Handle of the slip
% n_vector: Normal of the slip
% d_vector: Direction of the slip

% author: d.mercier@mpie.de

set(h_slip, ...
    'String', [ ...
    '(', ...
    num2str(n_vector), ...
    ') / [', ...
    num2str(d_vector), ...
    ']']);

end