% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function gui_handle = A_gui_plotmap
%% Function used to create the GUI

% authors: d.mercier@mpie.de / c.zambaldi@mpie.de

%% Initialization
if isempty(getenv('SLIP_TRANSFER_TBX_ROOT')) == 1
    errordlg('Run the path_management.m script !', 'File Error');
    return
end

%% Set GUI
gui = interface_map_init;

% Check if MTEX is installed
try
    gui_main = guidata(1);
    if isfield(gui_main, 'flag')
        if isfield(gui_main.flag, 'installation_mtex')
            if gui_main.flag.installation_mtex == 1
                gui_main_flag = 1;
                gui.flag.installation_mtex = 1;
            else
                gui_main_flag = 0;
            end
        else
            gui_main_flag = 0;
        end
    else
        gui_main_flag = 0;
    end
catch err
    gui_main_flag = 0;
    display(err.message);
end

if ~gui_main_flag
    gui.flag.installation_mtex = MTEX_check_install;
end

%% Initialization
format compact;
[startdir, f, ext] = fileparts(mfilename('fullpath'));
cd(startdir);

gui.rdm_TSL_dataset = 0;
gui.flag.newDataFlag = 0;
gui.tol.Tol_angle = 0;
gui.tol.Tol_angle_old = 0;
gui.COORDSYS_eulers = coordinate_convention(0);
gui.calculations.func2plot = 1;
gui.flag.pmparam2plot_value4Grains = 0;
gui.flag.pmparam2plot_value4GB = 0;
gui.flag.pmparam2plot_value4GB_old = 0;
gui.flag.pmparam2plot_value4GB_functype = 0;
gui.flag.pmparam2plot_value4GB_functype_old = 0;
gui.flag.pmlistsslips_ph1_old = 0;
gui.flag.pmlistsslips_ph2_old = 0;
gui.flag.pm_ph1_old = 0;
gui.flag.pm_ph2_old = 0;
gui.flag.pm_NumPh_old = 0;
gui.flag.pm_mat1_old = 0;
gui.flag.pm_mat2_old = 0;
gui.flag.initialization_axis = 1;

%% Importation of data from YAML config file (samples, paths...)
gui.config_map = interface_map_load_YAML_config_file;

gui.config_map.path_to_EBSD_data_examples = fullfile('EBSD_data_Examples');

%% Importation of data from YAML config file (paths of TSL data)
config_YAML_TSLdata = sprintf('config_gui_EBSDmap_data_path_%s.yaml', gui.config.username);

if exist(config_YAML_TSLdata, 'file') == 0
    %gui.config_map = struct();
else
    config_map_TSLOIM_data_path = ReadYaml(config_YAML_TSLdata);
    gui.config_map.TSLOIM_data_path_GF2 = config_map_TSLOIM_data_path.TSLOIM_data_path_GF2;
    gui.config_map.TSLOIM_data_path_RB  = config_map_TSLOIM_data_path.TSLOIM_data_path_RB;
end

if ~isfield(gui.config_map, 'TSLOIM_data_path_GF2')
    gui.config_map.TSLOIM_data_path_GF2 = gui.config_map.path_to_EBSD_data_examples;
end

if ~isfield(gui.config_map, 'TSLOIM_data_path_RB')
    gui.config_map.TSLOIM_data_path_RB = gui.config_map.path_to_EBSD_data_examples;
end

%% Window Coordinates Configuration
scrsize = screenSize;   % Get screen size
WX = 0.30 * scrsize(3); % X Position (bottom)
WY = 0.10 * scrsize(4); % Y Position (left)
WW = 0.65 * scrsize(3); % Width
WH = 0.75 * scrsize(4); % Height

%% Window configuration
gui.handles.TSLinterfWindow = figure('NumberTitle', 'off',...
    'PaperUnits', get(0,'defaultfigurePaperUnits'),...
    'Color', [0.9 0.9 0.9],...
    'Colormap', get(0,'defaultfigureColormap'),...
    'toolBar', 'figure',...
    'InvertHardcopy', get(0,'defaultfigureInvertHardcopy'),...
    'PaperPosition', [0 7 50 15],...
    'Position', [WX WY WW WH]);

gui.description = 'Analysis of Slip Transmission for an EBSD map - ';
guidata(gcf, gui);
gui.title_str = set_gui_title(gui, '');

gui.handles.gcf = gui.handles.TSLinterfWindow;

%% Customized menu
interface_map_custom_menu;

%% Choice of material and sample
gui.handles.Choice_material_title = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.97 0.13 0.02],...
    'HorizontalAlignment', 'center',...
    'String', 'Material_ID');

gui.handles.Choice_material_pm = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.02 0.94 0.13 0.03],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'String', gui.config_map.Material_IDs,...
    'Callback', 'gui = guidata(gcf); gui.config_map.Material_ID = gui.config_map.Material_IDs(get(gui.handles.Choice_material_pm, ''Value'')); guidata(gcf, gui)');

if isa(gui.config_map.Material_IDs, 'cell') == 1 || isa(gui.config_map.Material_ID, 'cell') == 1
    set(gui.handles.Choice_material_pm, 'Value', find(cell2mat(strfind(gui.config_map.Material_IDs, gui.config_map.Material_ID))));
end

gui.handles.Choice_sample_title = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.16 0.97 0.13 0.02],...
    'HorizontalAlignment', 'center',...
    'String', 'Sample_ID');

gui.handles.Choice_sample_pm = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.16 0.94 0.13 0.03],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'String', gui.config_map.Sample_IDs,...
    'Callback', 'gui = guidata(gcf); gui.config_map.Sample_ID = gui.config_map.Sample_IDs(get(gui.handles.Choice_sample_pm, ''Value'')); guidata(gcf, gui)');

if isa(gui.config_map.Sample_IDs, 'cell') == 1 || isa(gui.config_map.Sample_ID, 'cell') == 1
    set(gui.handles.Choice_sample_pm, 'Value', find(cell2mat(strfind(gui.config_map.Sample_IDs, gui.config_map.Sample_ID))));
end

%% Buttons to create random TSL data
gui.handles.cb_rdm_TSLdata = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.3 0.97 0.1 0.02],...
    'String', 'Random TSL data',...
    'Callback', 'interface_map_set_random_data(1);');

gui.handles.scale_rdm_TSLdata = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'slider',...
    'Min', 6, 'Max', 200, 'Value', 97,...
    'Position', [0.3 0.94 0.1 0.03],...
    'visible', 'off',...
    'Callback', 'interface_map_set_random_data(2);');

%% Buttons to browse in files
gui.handles.pbFileGF2 = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.91 0.2 0.03],...
    'String', '1) Import Grain File Type 2',...
    'Callback', 'gui = guidata(gcf); open_file_GF2; set(gui.handles.Eul_title, ''BackgroundColor'', [1 0 0]); set(gui.handles.pmcoordsyst, ''BackgroundColor'', [1 0 0]);');

gui.handles.FileGF2 = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.02 0.88 0.2 0.03],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'HorizontalAlignment', 'left',...
    'String', 'validation_grain_file_type2.txt');

gui.handles.pbFileRB = uicontrol('Parent',gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.85 0.2 0.03],...
    'String', '2) Import Reconstr. Bound. File',...
    'Callback', 'gui = guidata(gcf); open_file_RB; set(gui.handles.Eul_title, ''BackgroundColor'', [1 0 0]); set(gui.handles.pmcoordsyst, ''BackgroundColor'', [1 0 0]);');

gui.handles.FileRB = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.02 0.82 0.2 0.03],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'HorizontalAlignment', 'left',...
    'String', 'validation_reconstructed_boundaries.txt');

%% Setting of Euler angles
gui.handles.Eul_title = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.23 0.91 0.06 0.02],...
    'HorizontalAlignment', 'left',...
    'String', 'Coord. Syst.');

gui.handles.pmcoordsyst = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.23 0.89 0.06 0.02],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'String',{'X right, Y up'; 'X up, Y left'; ...
    'X left, Y down'; 'X down, Y right (TSL default)'; ...
    'X right, Y down'; 'X up, Y right'; ...
    'X left, Y up'; 'X down, Y left'},...
    'Value', 1,...
    'Callback', 'gui = guidata(gcf); interface_map_set_coordinate_convention; set(gui.handles.Eul_title, ''BackgroundColor'', [0.9 0.9 0.9]); set(gui.handles.pmcoordsyst, ''BackgroundColor'', [0.9 0.9 0.9]);');

%% Setting of Scale Unit
gui.handles.Unit_title = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.23 0.85 0.06 0.02],...
    'HorizontalAlignment', 'left',...
    'String', 'Unit');

gui.handles.pm_unit = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.23 0.83 0.06 0.02],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'String', {'nm';'µm';'mm'},...
    'Value', 2,...
    'Callback', 'interface_map_plotmap(0);');

%% Plot EBSD map (all grains)
gui.handles.pbFileScanData = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.78 0.15 0.03],...
    'String', '3) Import .ang file with MTEX',...
    'Callback', 'interface_map_MTEX_getEBSD;');

gui.handles.pbPlotEBSDMap = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.18 0.78 0.11 0.03],...
    'String', 'Plot EBSD Map',...
    'visible', 'off',... % 'on' when .ang data are loaded by user using MTEX routine
    'Callback', 'try interface_map_MTEX_plotEBSDdata(ebsd); catch helpdlg(''Save ebsd as a variable in the Matlab workspace, when loading ang. file...''); end');

gui.handles.pbPlotStatGrain = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.18 0.75 0.11 0.03],...
    'String', 'Plot Grain Stat.',...
    'visible', 'off',... % 'on' when .ang data are loaded by user using MTEX routine
    'Callback', 'try interface_map_MTEX_plotGrainsStat(ebsd); catch helpdlg(''Save ebsd as a variable in the Matlab workspace, when loading ang. file...''); end');

%% Setting of the number of Phases (1 or 2)
gui.handles.Settings = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.75 0.06 0.02],...
    'HorizontalAlignment', 'left',...
    'String', '4) Settings');

gui.handles.NumPh_title = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.72 0.09 0.02],...
    'HorizontalAlignment', 'left',...
    'String', 'Number of Phases');

gui.handles.NumPh = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.02 0.7 0.03 0.02],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'String', '2');

%% Plot and Setting of Material and Structure
[gui.handles.Mat1, gui.handles.pmMat1, gui.handles.Struct1, gui.handles.pmStruct1, gui.handles.listslips1, gui.handles.pmlistslips1] = interface_map_material('#1', [0.02 0.67 0.11 0.02], 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); gui.flag.new_slip_families = 1; guidata(gcf, gui); interface_map_plotmap', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); gui.flag.new_slip_families = 1; guidata(gcf, gui); interface_map_plotmap(0);');
[gui.handles.Mat2, gui.handles.pmMat2, gui.handles.Struct2, gui.handles.pmStruct2, gui.handles.listslips2, gui.handles.pmlistslips2] = interface_map_material('#2', [0.15 0.67 0.11 0.02], 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); gui.flag.new_slip_families = 1; guidata(gcf, gui); interface_map_plotmap', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); gui.flag.new_slip_families = 1; guidata(gcf, gui); interface_map_plotmap(0);');
set(gui.handles.pmStruct2, 'Value', 2); % To have a bcc phase for material #1 and fcc phase for material #2

%% Stress Tensor
gui.handles.StressTensorStr = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.46 0.11 0.02],...
    'HorizontalAlignment', 'center',...
    'String', 'Stress tensor :');

gui.handles.ST_s11 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.02 0.440 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s12 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.06 0.440 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s13 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.10 0.440 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s21 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.02 0.415 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s22 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.06 0.415 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s23 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.10 0.415 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s31 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.02 0.390 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s32 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.06 0.390 0.03 0.02], 'String', '0', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');
gui.handles.ST_s33 = uicontrol('Parent', gui.handles.TSLinterfWindow, 'Units', 'normalized', 'BackgroundColor', [0.9 0.9 0.9], 'Position', [0.10 0.390 0.03 0.02], 'String', '1', 'Style', 'edit', 'Callback', 'gui = guidata(gcf); set(gui.handles.pmparam2plot4GB, ''Value'', 1); set(gui.handles.pmparam2plot4Grains, ''Value'', 1); guidata(gcf, gui); interface_map_plotmap(0);');

%% GB Map Plot settings
gui.handles.cbgrnum = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.02 0.35 0.12 0.02],...
    'String', 'Grain Number',...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.cbgbnum = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.02 0.33 0.12 0.02],...
    'String', 'GB Number',...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.cbphase = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.02 0.31 0.12 0.02],...
    'String', 'Phase',...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.cbunitcell = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.02 0.29 0.12 0.02],...
    'String', 'Unit cell',...
    'Value', 1,...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.cbdatavalues = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.02 0.27 0.12 0.02],...
    'String', 'Plot of values',...
    'Value', 0,...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.cbsliptraces = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.15 0.35 0.12 0.02],...
    'String', 'Plot of Slip Traces',...
    'Visible', 'off',...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.param2Scale4GBs = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'HorizontalAlignment', 'left',...
    'Position', [0.02 0.24 0.12 0.02],...
    'String', 'GB parameter to plot');

gui.handles.pmparam2plot4GB = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.02 0.22 0.12 0.02],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'Value', 1,...
    'String', {'None';'m'' (highest values)';'m'' (lowest values)';...
    'm'' with slips with highest Schmid factors';'m'' with slips with highest resolved shear stress';...
    'Max-10% of highest values of m''';'Min+10% of lowest values of m''';...
    'Misorientation';'C-axis Misor.';...
    'Max residual Burgers vector';'Min residual Burgers vector';...
    'N-factor max'; 'N-factor min';...
    'Max GB Schmid Factor';...
    'Other Function'},...
    'Callback', 'interface_map_plotmap(1,1);');

gui.handles.param2Scale4Grains = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'HorizontalAlignment', 'left',...
    'Position', [0.15 0.24 0.12 0.02],...
    'String', 'Grain parameter to plot');

gui.handles.pmparam2plot4Grains = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.15 0.22 0.12 0.02],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'Value', 1,...
    'String', {'None';...
    'Slip with highest Generalized Schmid Factor';...
    'Slip with highest Resolved Shear Stress';...
    'Plot of slip trace for Slip with highest Generalized Schmid Factor'},...
    'Callback', 'interface_map_plotmap(1,1);');

%% Legend of slip traces (colors used for slips plotted inside unit cells for each grain)
gui.handles.cblegend = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.15 0.33 0.12 0.02],...
    'String', 'Legend of Slip Traces',...
    'Visible', 'off',...
    'Value', 0,...
    'Callback', 'interface_map_plotmap(0);');

%% Scalebar for the size of unit cells
gui.handles.scale_unitcell_str = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.15 0.29 0.12 0.02],...
    'String', 'Size of Unit Cells');

gui.handles.scale_unitcell_bar = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'slider',...
    'Min', 0, 'Max', 2, 'Value', 1,...
    'Position', [0.15 0.27 0.12 0.02],...
    'Callback', 'interface_map_plotmap(0);');

%% Plot of a specific bicrystal
gui.handles.GB2plot = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',....
    'Style', 'text',...
    'HorizontalAlignment', 'left',...
    'Position', [0.02 0.17 0.08 0.02],...
    'String', {'GB number to plot'});

gui.handles.numGB2plot = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'BackgroundColor', [0.9 0.9 0.9],...
    'Position', [0.02 0.15 0.08 0.02],...
    'String', '1');

gui.handles.pbGBplot = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.11 0.15 0.1 0.04],...
    'String', 'PLOT BICRYSTAL',...
    'Callback', 'A_gui_plotGB_Bicrystal(guidata(gcf));');

%% GB and Grain numbers
gui.handles.GB_totalnumber_title = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',....
    'Style', 'text',...
    'HorizontalAlignment', 'left',...
    'Position', [0.42 0.94 0.1 0.02],...
    'String', {'Number of GBs :'});

gui.handles.GB_totalnumber_value = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'BackgroundColor', [0.9 0.9 0.9],...
    'Position', [0.52 0.94 0.03 0.02],...
    'String', '');

gui.handles.Grain_totalnumber_title = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',....
    'Style', 'text',...
    'HorizontalAlignment', 'left',...
    'Position', [0.42 0.97 0.1 0.02],...
    'String', {'Number of Grains :'});

gui.handles.Grain_totalnumber_value = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'BackgroundColor', [0.9 0.9 0.9],...
    'Position', [0.52 0.97 0.03 0.02],...
    'String', '');

%% Scalebar for the number of total grain boundaries (smoothing)
gui.handles.scale_gb_segments_str = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.42 .91 0.13 0.02],...
    'String', 'Grain boundaries smoothing');

gui.handles.scale_gb_segments_bar = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'slider',...
    'Min', 0, 'Max', 180, 'Value', 0,...
    'Position', [0.42 .89 0.13 0.02],...
    'Callback', 'interface_map_plotmap(1,1);');

%% Button to save new GBs dataset (after smoothing for example)
gui.handles.pbsave_newGBs = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.75 0.93 0.13 0.03],...
    'String', 'SAVE GBs',...
    'Callback', 'interface_map_save_TSL_data;');

%% Setting of microstructure map Axis...
gui.handles.titlecolorbar = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.57 0.97 0.13 0.02],...
    'HorizontalAlignment', 'center',...
    'String', 'Style of Colorbar');

gui.handles.pmcolorbar = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.57 0.94 0.13 0.03],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'String', 'jet|autumn|bone|colorcube|cool|copper|flag|gray|hot|hsv|lines|pink|prism|spring|summer|white|winter',...
    'Value', 1,...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.titlecolorbar_loc = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.57 0.92 0.13 0.02],...
    'HorizontalAlignment', 'center',...
    'String', 'Location of Colorbar');

gui.handles.pmcolorbar_loc = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.57 0.89 0.13 0.03],...
    'BackgroundColor', [0.9 0.9 0.9],...
    'String', 'North|South|East|West|NorthOutside|SouthOutside|EastOutside|WestOutside',...
    'Value', 5,...
    'Callback', 'interface_map_plotmap(0);');

gui.handles.date_str_interface = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'text',...
    'String', datestr(datenum(clock),'mmm.dd,yyyy HH:MM'),...
    'Position', [0.75 0.97 0.13 0.025]);

gui.handles.pbsavefigure = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.75 0.89 0.13 0.03],...
    'String', 'SAVE FIGURE',...
    'Callback', 'gui = guidata(gcf); save_figure(gui.config_map.pathname_reconstructed_boundaries_file, gui.handles.AxisGBmap); set(gui.handles.TSLinterfWindow, ''Color'', [1 1 1]*.9);');

%% EBSD Map
gui.handles.PlotMapAxis = axes('Parent', gui.handles.TSLinterfWindow, ...
    'Position', [0.94 0.94 0.02 0.02]);

gui.handles.AxisGBmap = axes('Parent', gui.handles.TSLinterfWindow,...
    'Position', [0.375 0.078 0.6 0.75]);

set(gcf, 'CurrentAxes', gui.handles.AxisGBmap);

%% Clear all & Save & Quit & Help
gui.handles.pbhelp = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.09 0.19 0.05],...
    'String', 'HELP',...
    'Callback', 'gui = guidata(gcf); web(gui.config.doc_path_root);');

gui.handles.pbclearall = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.03 0.06 0.05],...
    'String', 'RESET',...
    'Callback', 'close_windows(gcf); A_gui_plotmap;');

gui.handles.pbsav = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.085 0.03 0.06 0.05],...
    'String', 'SAVE DATA',...
    'Callback', 'uisave();');

gui.handles.pbfinishsav = uicontrol('Parent', gui.handles.TSLinterfWindow,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.15 0.03 0.06 0.05],...
    'String', 'CLOSE',...
    'Callback', 'finishsav;');

%% Encapsulation of data
gui.flag.initialization_axis = 1;
guidata(gcf, gui);

%% Set materials and slips families
interface_map_material_definition;
interface_map_list_slips(gui.handles.pmStruct1, gui.handles.pmStruct2, gui.handles.pmlistslips1, gui.handles.pmlistslips2, 2, 1, 1);

%% Initialization of the EBSD map interface
interface_map_set_coordinate_convention;

gui_handle = gui.handles.TSLinterfWindow;

%% Encapsulation of data
gui = guidata(gcf); guidata(gcf, gui);

end
