% Copyright 2013 Max-Planck-Institut für Eisenforschung GmbH
function plot_unit_cell(refresh_unit_cell, varargin)
%% Function used to plot unique lattice cell with a slip system for a given grain
% refresh_unit_cell: flag to set the refresh of the unit cell
% authors: d.mercier@mpie.de

if nargin == 0
    refresh_unit_cell = 0;
end

if ~refresh_unit_cell
    gui = struct();
    
    %% Windows Coordinates Configuration
    scrsize = screenSize;   % Get screen size
    WX = 0.35 * scrsize(3); % X Position (bottom)
    WY = 0.35 * scrsize(4); % Y Position (left)
    WW = 0.40 * scrsize(3); % Width
    WH = 0.50 * scrsize(4); % Height
    
    %% Creation of the window
    gui.handles.UCPlotWin = figure('Name', 'Plot of unit cell',...
        'NumberTitle', 'off',...
        'PaperUnits', get(0,'defaultfigurePaperUnits'),...
        'Color', [0.9 0.9 0.9],...
        'Colormap', get(0,'defaultfigureColormap'),...
        'toolBar', 'figure',...
        'InvertHardcopy', get(0,'defaultfigureInvertHardcopy'),...
        'PaperPosition', [0 7 50 15],...
        'Position', [WX WY WW WH]);
    
    %% UCPlotWin configuration
    gui.handles.Structure = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left',...
        'Position', [0.2 0.9 0.2 0.05],...
        'String', 'Structure',...
        'HorizontalAlignment','center',...
        'Style', 'text');
    
    gui.handles.EditStruct = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Position', [0.2 0.8 0.2 0.1],...
        'String', ['hcp';'bcc';'fcc'],...
        'Style', 'popupmenu',...
        'Value', 1,...
        'callback', 'plot_unit_cell(1)');
    
    gui.handles.TitleSlip = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left',...
        'Position', [0.6 0.9 0.2 0.05],...
        'String', 'Slip',...
        'HorizontalAlignment','center',...
        'Style', 'text');
    
    guidata(gcf, gui);
    if get(gui.handles.EditStruct, 'Value') == 1
        list_slip_families = {'No slip';'Basal';'Prismatic_1 <a>';'Prismatic_2 <a>';'Pyramidal <a>'; 'Pyramidal_1 <c+a>'; 'Pyramidal_2 <c+a>}'; 'Twin T1'; 'Twin T2'; 'Twin C1'; 'Twin C2'};
    elseif get(gui.handles.EditStruct, 'Value') == 2
        list_slip_families = {'No slip'; 'Slips{110}'; 'Slips{211}'; 'Slips{321}'; 'Twin #4'};
    elseif get(gui.handles.EditStruct, 'Value') == 3
        list_slip_families = {'No slip'; 'Slips{111}'; 'Twins{111}'};
    end
    
    gui.handles.pmSlip = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Position', [0.6 0.8 0.2 0.1],...
        'String', list_slip_families,...
        'Style', 'popupmenu',...
        'Value', 1,...
        'callback', 'plot_unit_cell(1)');
    
    gui.handles.EulerAngle1 = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left',...
        'Position', [0.05 0.7 0.28 0.08],...
        'String', 'Bunge Angle 1 (°)',...
        'Style', 'text');
    
    gui.handles.EditEulerAngle1 = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Position', [0.05 0.62 0.28 0.08],...
        'String', '0',...
        'Style', 'edit',...
        'callback', 'plot_unit_cell(1)');
    
    gui.handles.EulerAngle2 = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left',...
        'Position', [0.36 0.7 0.28 0.08],...
        'String', 'Bunge Angle 2 (°)',...
        'Style', 'text');
    
    gui.handles.EditEulerAngle2 = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Position', [0.36 0.62 0.28 0.08],...
        'String', '0',...
        'Style', 'edit',...
        'callback', 'plot_unit_cell(1)');
    
    gui.handles.EulerAngle3 = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left',...
        'Position', [0.67 0.7 0.28 0.08],...
        'String', 'Bunge Angle 3 (°)',...
        'Style', 'text');
    
    gui.handles.EditEulerAngle3 = uicontrol('Parent', gui.handles.UCPlotWin,...
        'Units', 'normalized',...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Position', [0.67 0.62 0.28 0.08],...
        'String', '0',...
        'Style', 'edit',...
        'callback', 'plot_unit_cell(1)');
    
    gui.handles.axis = subplot(5, 2, [5 10]);
    axis off;
    
    %% Encapsulation of data into the GUI
    guidata(gcf, gui);
    
end

%% Get encapsulated data from the GUI
gui = guidata(gcf);

if refresh_unit_cell
    if gui.list_slip_family_old ~= get(gui.handles.EditStruct, 'Value')
        set(gui.handles.pmSlip, 'Value', 1);
    end
    
    if get(gui.handles.EditStruct, 'Value') == 1
        list_slip_families = {'No slip';'Basal';'Prismatic_1 <a>';'Prismatic_2 <a>';'Pyramidal <a>'; 'Pyramidal_1 <c+a>'; 'Pyramidal_2 <c+a>}'; 'Twin T1'; 'Twin T2'; 'Twin C1'; 'Twin C2'};
    elseif get(gui.handles.EditStruct, 'Value') == 2
        list_slip_families = {'No slip'; 'Slips{110}'; 'Slips{211}'; 'Slips{321}'; 'Twin #4'};
    elseif get(gui.handles.EditStruct, 'Value') == 3
        list_slip_families = {'No slip'; 'Slips{111}'; 'Twins{111}'};
    end
    set(gui.handles.pmSlip, 'String', list_slip_families);
    
    %% Clear axis
    cla;
    
    %% Get Euler angles
    gui.eulers(1) = str2num(get(gui.handles.EditEulerAngle1, 'String'));
    gui.eulers(2) = str2num(get(gui.handles.EditEulerAngle2, 'String'));
    gui.eulers(3) = str2num(get(gui.handles.EditEulerAngle3, 'String'));
    
    %% Get Structure and Slip to plot
    if get(gui.handles.EditStruct, 'Value') == 1
        gui.structure = 'hcp';
        if get(gui.handles.pmSlip, 'Value') == 1
            gui.Slipplot = 0;
        elseif get(gui.handles.pmSlip, 'Value') == 2
            gui.Slipplot = 1;
        elseif get(gui.handles.pmSlip, 'Value') == 3
            gui.Slipplot = 4;
        elseif get(gui.handles.pmSlip, 'Value') == 4
            gui.Slipplot = 7;
        elseif get(gui.handles.pmSlip, 'Value') == 5
            gui.Slipplot = 10;
        elseif get(gui.handles.pmSlip, 'Value') == 6
            gui.Slipplot = 16;
        elseif get(gui.handles.pmSlip, 'Value') == 7
            gui.Slipplot = 28;
        elseif get(gui.handles.pmSlip, 'Value') == 8
            gui.Slipplot = 34;
        elseif get(gui.handles.pmSlip, 'Value') == 9
            gui.Slipplot = 40;
        elseif get(gui.handles.pmSlip, 'Value') == 10
            gui.Slipplot = 46;
        elseif get(gui.handles.pmSlip, 'Value') == 11
            gui.Slipplot = 52;
        end
        
    elseif get(gui.handles.EditStruct, 'Value') == 2
        gui.structure = 'bcc';
        if get(gui.handles.pmSlip, 'Value') == 1
            gui.Slipplot = 0;
        elseif get(gui.handles.pmSlip, 'Value') == 2
            gui.Slipplot = 1;
        elseif get(gui.handles.pmSlip, 'Value') == 3
            gui.Slipplot = 13;
        elseif get(gui.handles.pmSlip, 'Value') == 4
            gui.Slipplot = 25;
        elseif get(gui.handles.pmSlip, 'Value') == 5
            gui.Slipplot = 49;
        end
        
    elseif get(gui.handles.EditStruct, 'Value') == 3
        gui.structure = 'fcc';
        if get(gui.handles.pmSlip, 'Value') == 1
            gui.Slipplot = 0;
        elseif get(gui.handles.pmSlip, 'Value') == 2
            gui.Slipplot = 1;
        elseif get(gui.handles.pmSlip, 'Value') == 3
            gui.Slipplot = 13;
        end
    end
    
    %% Plot Unit Cell
    vis_lattice(gui.structure, gui.eulers, gui.Slipplot);
end

gui.list_slip_family_old = get(gui.handles.EditStruct, 'Value');

%% Encapsulation of data into the GUI
guidata(gcf, gui);

end